export const productFlavors = [
  {
    id: "original",
    name: "Original",
    eyebrow: "Core Formula",
    headline: "Black Bagiraa at full voltage.",
    description:
      "Dark, controlled, and sharp. The Original blend is tuned for focus-first energy with a smoother premium finish.",
    benefits: ["High-drive caffeine", "B-vitamin support", "Night-shift endurance"],
    notes: ["Burnt citrus edge", "Deep roasted finish", "Clean control"],
    accent: "#ff6a00",
    accentSoft: "#ffc067",
    surface: "#050505",
    panel: "#101010",
    panelSoft: "#1a1a1a",
    text: "#f8f1e7",
    liquid: "#1c140f",
    glass: "#6f6763",
    cap: "#111111",
    label: {
      backgroundTop: "#0a0a0c",
      backgroundBottom: "#1b1207",
      textPrimary: "#fff3df",
      textSecondary: "#d3b28e",
      detail: "#7a5a34",
    },
    metrics: ["120 MG CAFFEINE", "B3 B6 B12", "200 ML"],
  },
  {
    id: "orange-ginger",
    name: "Orange Ginger",
    eyebrow: "Citrus Drive",
    headline: "Bright lift with a spiced finish.",
    description:
      "Orange Ginger opens with a fresher attack and lands with a cleaner warmth, perfect for daytime momentum and fast resets.",
    benefits: ["Electrolyte freshness", "Ginger warmth", "Fast daytime lift"],
    notes: ["Citrus snap", "Warm ginger close", "Crisp aftertaste"],
    accent: "#ff5b2e",
    accentSoft: "#ffbe70",
    surface: "#140704",
    panel: "#20100c",
    panelSoft: "#2d1710",
    text: "#fff4ea",
    liquid: "#ff5224",
    glass: "#f4b79d",
    cap: "#f2ece4",
    label: {
      backgroundTop: "#fff7ef",
      backgroundBottom: "#ffd29e",
      textPrimary: "#27140c",
      textSecondary: "#8a4d28",
      detail: "#f18937",
    },
    metrics: ["CITRUS BOOST", "GINGER EDGE", "200 ML"],
  },
  {
    id: "pineapple-masala",
    name: "Pineapple Masala",
    eyebrow: "Tropical Charge",
    headline: "Tropical brightness, beast-mode finish.",
    description:
      "Pineapple Masala delivers a louder, sunlit flavour profile with a spiced backbone that still feels polished and premium.",
    benefits: ["Tropical flavour hit", "Smooth sparkling body", "Longer-feel energy"],
    notes: ["Golden pineapple", "Masala spice", "Soft sparkling tail"],
    accent: "#ffd21f",
    accentSoft: "#fff1a2",
    surface: "#100d02",
    panel: "#181404",
    panelSoft: "#28210a",
    text: "#fff9db",
    liquid: "#f4dd1e",
    glass: "#f8e88b",
    cap: "#f2efe5",
    label: {
      backgroundTop: "#fffbe5",
      backgroundBottom: "#ffd84d",
      textPrimary: "#2b2402",
      textSecondary: "#796300",
      detail: "#f8ba0d",
    },
    metrics: ["TROPICAL SPICE", "SPARKLING ENERGY", "200 ML"],
  },
];
